title: Los Angeles Coronavirus Cases
baseurl: "/la-coronavirus-cases"
url: ""
timezone: America/Tijuana

exclude:
  - assets/js/src
  - Gemfile*
  - node_modules
  - package*.json
  - README.md
  - vendor
  - webpack.config.js
